name: Python workflow

on: [push]

on: 
  push:
    branches:
    - main

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /github/workflows/requirements.txt

    - name: Run Python script
      run: python ./github/workflows/script.py

