name: Test-DevOPs Pipeline
#run-name: ${{ github.actor }} is learning GitHub Actions
#evento que irá adicionar a pipeline
on: 
  push:
    branches:
    - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2