name: Python CI

on:
  push:
    branches:
      - r2-2023-new

jobs:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python Script
      run: |
        python script.py